spring:
  application:
    name: tourizm
  datasource:
    url: jdbc:h2:mem:tourismdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
